### ISSUE TITLE
hi，I have some questions about this project

### ISSUE THREAD

**Issue by wghust** [yunjiali/synote.js#1]
How can run the client .When I use this  "grunt server", I will have this warn.

``` js
Running "connect:livereload" (connect) task
Verifying property connect.livereload exists in config...OK
File: [no files]
Options: protocol="http", port=9000, hostname="localhost", base=".", directory=null, keepalive=false, debug=false, livereload=35729, open, useAvailablePort=false, middleware=undefined
Warning: undefined is not a function Use --force to continue.
```

what can I do?

**Comment by yunjiali** [comment]
Hi, have you tried "grunt serve" instead of "grunt server"?

**Comment by wghust** [comment]
@yunjiali sorry, I have use this 'grunt serve', the same warn~~~

**Comment by wghust** [comment]
is this codes have some problem?

``` js
middleware: function (connect) {
    return [
       connect.static('.tmp'),
       connect().use(
              '/bower_components',
              connect.static('./bower_components')
              ),
             connect.static(appConfig.app)
             ];
           }

```

**Comment by wghust** [comment]
the key is "middleware=undefined"~~~

**Comment by yunjiali** [comment]
I see. I will have a check. I used Yeoman AngularJs from the very first beginning, and I don't recall I have changed anything about 'middleware'.

**Comment by wghust** [comment]
@yunjiali  so, I find these codes have no mistakes. I use `grunt serve --force -v` to ignore the warn. But I can't find the route. Can you supply the README.md?

**Comment by yunjiali** [comment]
Sorry, I am not sure if I understand your question correctly. For the route, do you mean http://localhost:9000?

**Comment by wghust** [comment]
@yunjiali no, If I don't solve the warn of middleware. I can't open the website of "http://localhost:9000"

**Comment by wghust** [comment]
@yunjiali  when I open 'localhost:9000'，it will have this error

```
Error: [$injector:unpr] Unknown provider: $$jqLiteProvider <- $$jqLite <- $animate <- $compile
http://errors.angularjs.org/1.3.0/$injector/unpr?p0=%24%24jqLiteProvider%20%3C-%20%24%24jqLite%20%3C-%20%24animate%20%3C-%20%24compile
```

is the version problem?
